<?xml version="1.0" encoding="utf-8"?><Database Name="EATFSConverter" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=KAMIL\SQLEXPRESS;Initial Catalog=EATFSConverter;Integrated Security=True" SettingsObjectName="EAtoTFSConverter.Properties.Settings" SettingsPropertyName="EATFSConverterConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Step" Member="Steps">
    <Type Name="Step">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Result" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SubjectId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="EAScenario_Step" Member="EAScenario" ThisKey="SubjectId" OtherKey="SubjectId" Type="EAScenario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EAScenario" Member="EAScenarios">
    <Type Name="EAScenario">
      <Column Name="SubjectId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="XmiId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="EAScenario_Step" Member="Steps" ThisKey="SubjectId" OtherKey="SubjectId" Type="Step" />
      <Association Name="EAScenario_UseCase" Member="UseCases" ThisKey="SubjectId" OtherKey="SubjectId" Type="UseCase" />
    </Type>
  </Table>
  <Table Name="dbo.UseCase" Member="UseCases">
    <Type Name="UseCase">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="SubjectId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="EAScenario_UseCase" Member="EAScenario" ThisKey="SubjectId" OtherKey="SubjectId" Type="EAScenario" IsForeignKey="true" />
    </Type>
  </Table>
</Database>